Polls/urls.py
from django.urls import path 
from . import views
app_name = "Polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.questionDetail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

PollsInDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("Polls.urls")),
]

Polls/models.py
import datetime

#django modules
from django.db import models
from django.utils import timezone

#models 
class Question(models.Model):
    questionText = models.CharField(max_length=200)
    pubDate = models.DateTimeField("date published")
    
    def __str__(self):
        return self.questionText
    def wasPublishedRecently(self):
        return self.pubDate >= timezone.now() - datetime.timedelta(days=1)
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choiceText = models.CharField(max_length=300)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choiceText

Polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.db.models import F
from django.urls import reverse

# Create your views here.
def index(request):
    questionList = Question.objects.order_by("-pubDate")[:5]
    template = loader.get_template("Polls/index.html")
    context = {
        "questionList" : questionList,
    }
    return HttpResponse(template.render(context, request))

def questionDetail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")
    return render(request, "polls/detail.html", {"question":question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "Polls/results.html", {"question" : question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selectedChoice = question.choice_set.get(pk=request.POST["choice"])
    except(KeyError, Choice.DoesNotExist):
        return render(request, "polls/detail.html", {"question":question, "errorMessage":"You didn't select a choice.",})
    else:
        selectedChoice.votes = F("votes") + 1
        selectedChoice.save()
        return HttpResponseRedirect(reverse("Polls:results", args=(question.id,)))

Polls/templates/Polls/detail.html
<!-- <h1> {{question}} </h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choiceText }}</li>
    {% endfor %}
</ul> -->

<form action="{% url 'Polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.questionText }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choiceText }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    <a href="{% url 'Polls:index' %}">Home</a>
    <!-- <input type="submit" value="Home"> -->
    </form>

Polls/templates/Polls/index.html
{% if questionList %}
    <ul>
    {% for question in questionList %}
        <li><a href="/polls/{{question.id}}/">{{question.questionText}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p> No Polls are available</p>
{% endif %}

Polls/templates/Polls/results.html
<h1>{{ question.questionText }}</h1>

<ul>
    {%for choice in question.choice_set.all %}
        <li> {{ choice.choiceText }} -- {{ choice.votes }} vote {{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>
<a href="{% url 'Polls:detail' question.id %}"> Vote Again ?</a>
<a href="{% url 'Polls:index' %}">Home</a>